name: Deploy To Test
on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: 
      name: test
      url: https://dev.pokercoachingwp.com/

    steps:
      - name: let's started! 🎉
        run: | 
          echo "name of branch is ${{ github.ref }} and repository is ${{ github.repository }}." 
          echo "The repository has been cloned to the runner. 🖥️ The workflow is now ready to test your code on the runner."

      - name: Check out repository code
        uses: actions/checkout@v3

      - name: List files in the repository
        run: |
          ls -la ${{ github.workspace }}
          echo "This job's status is ${{ job.status }}."

      - name: rsync deployments
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
            username: ${{ secrets.DEPLOY_USERNAME }}
            server: ${{ secrets.DEPLOY_HOST }}
            port: ${{ secrets.FTP_PORT }}
            local_path: './*'
            remote_path: '/testpc/testpc-www/test'
            sftp_only: true
            password: ${{ secrets.DEPLOY_PASS }}

      - run: echo "deployed to url https://dev.pokercoachingwp.com/"
